### ISSUE TITLE
Usage with Pega and Constellation 8.7 

### ISSUE THREAD

**Issue by Virusmater** [pegasystems/react-sdk#26]
Is it possible to use this SDK with Pega 8.7 and Constellation 8.7? Package on Marketplace supports only 8.6.3
If it is not - when is planned to release version for Pega 8.7?

**Comment by JEAxero** [comment]
Hi. The Pega Marketplace release to support Pega 8.7 was released last Friday. Note that there are separate downloads for the React SDK depending on whether you want to work with Pega Infinity 8.6 or Pega Infinity 8.7. And, as noted in the Reacat SDK Guide included in the Marketplace download, to use 8.7, you pull from this repo's "main" branch, and to use 8.6, you pull code from this repo's "release/8.6" branch.

https://community.pega.com/marketplace/components/react-sdk
