### ISSUE TITLE
Loose focus input

### ISSUE THREAD

**Issue by houssem-hichri** [pegasystems/react-sdk#47]
**Describe the bug**
On every keystroke the input field re-renders and loose focus.

**To Reproduce**
Steps to reproduce the behaviour:
The issue appear only under the second screen for our private COSMOS react application.
1. Start the SDK in embedded mode
2. Fill in and submit first screen
3. Fill in any text input
4. The input will loose focus on every typed character 

**Expected behaviour**
Avoid multiple re-renders or auto-focus the active input.

**Screenshots**
[recording](https://jmp.sh/DZYWjiN)

**Desktop (please complete the following information):**
 - IOS
 - chrome
 - Version 99.0.4844.74

**Comment by JEAxero** [comment]
Thanks for confirming!

**Comment by JEAxero** [comment]
Hi! I just wanted to let you know that the problem you reported with this issue has been resolved in PR 52:
https://github.com/pegasystems/react-sdk/pull/52

Thanks for reporting it and thanks for your patience while we fixed it.

**Comment by houssem-hichri** [comment]
Hi team! Great job, the issue is resolved now, thank you.

**Comment by JEAxero** [comment]
Thanks! I'll close the issue now that I know we've addressed it!
