### ISSUE TITLE
Approve/reject not working on SDK

### ISSUE THREAD

**Issue by oussamaInnovationTeam** [pegasystems/react-sdk#480]
Issue Description:
 
We are encountering a problem within the SDK where the "Approve" and "Reject" actions are non-responsive. When users attempt to perform these actions, no subsequent events or changes occur in the application. This issue persists despite attempts to customize the behavior using React or Pega.
 for pega it is working correctly
on sdk not working
Steps to Reproduce:
 create Approve/reject step shape from pega configure the flow to change stage to resolution once approve and change status resolve-completed and rejected once rejected it work perfectly from in pega platform but no action happen when we tried on the sdk

**Comment by niallriddell** [comment]
Which Infinity and SDK version are you seeing this issue on?

**Comment by tumms2021389** [comment]
This was fixed as part React SDK 24.1.10 version

**Comment by niallriddell** [comment]
Closing as fixed in latest release
