### ISSUE TITLE
Open question - Vulnerability and malware scan?

### ISSUE THREAD

**Issue by AdityaKulkarni2024** [pegasystems/react-sdk#498]
I was wondering, since the repo is available to public internet and anyone could download and start using it. just wanted to understand on the vulnerability and malware scan of the code in it.
Does Pega have any scanning done already before publishing the code on pegasystems/react-sdk ? 
If yes, what kind of scans are completed ?

**Comment by niallriddell** [comment]
We use dependabot and mend scan.  Mend scan was originally run when the repo was open sourced and has now been enabled to run weekly also.

**Comment by niallriddell** [comment]
Closing this as consumer of repository can also run local scans if above is not enough.
