### ISSUE TITLE
dx-component-builder-sdk authenticate success -> wrong exit code

### ISSUE THREAD

**Issue by wimbarelds** [pegasystems/react-sdk#506]
**Describe the bug**
When you run the "authenticate" task from `@pega/dx-component-builder-sdk` and log in succesfully, the exit code is 1 (which means, error), it should be 0 (which means success).

**To Reproduce**
1. `npx @pega/dx-component-builder-sdk authenticate`
2. Authenticate
3. On windows: `echo %ERRORLEVEL%`, on MacOS `echo $?`
4. See error-code (1)

**Expected behavior**
When login is successful, exit code = 0

**Screenshots**
Not applicable

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser N/A
 - Version N/A

**Additional context**

https://en.wikipedia.org/wiki/Exit_status#Shell_and_scripts

> For the shell's purposes, a command which exits with a zero exit status has succeeded. A nonzero exit status indicates failure.

To the best of my knowledge, this is the only place where an incorrect exit code is returned.

**Comment by timjmartel** [comment]
Created Pega internal Agile Studio item BUG-885298 to track issue.

**Comment by niallriddell** [comment]
Closed as being tracked as internal BUG.  Will be fixed in upcoming release.
