### ISSUE TITLE
Incorrect redirect_uri when access https://localhost:3502/portal on clear session

### ISSUE THREAD

**Issue by Virusmater** [pegasystems/react-sdk#54]
Using latest available code from github main branch + Pega 8.7.1 + latest available SDK from marketplace
Was following all steps in the guide, but there is an error somewhere.
After installation I'm trying to access https://localhost:3502/portal, but it redirects me to 
`https://<pega-instance>/prweb/PRRestService/oauth2/v1/authorize?client_id=25795373220702300272&response_type=code&redirect_uri=https://localhost:3502/&scope=openid&state=aHR0cHM6Ly9sb2NhbGhvc3Q6MzUwMg==&code_challenge=bcED0Ml17BPLHqG6_NTfY-jVUiBt9iQRGTZZiRndYZ8&code_challenge_method=S256&authentication_service=pega&enable_psyncId=true`
As you can see redirect_uri doesn't have /portal for some reason and therefore auth fails because such redirect isn't allowed in OAuth rule.
After adding https://localhost:3502/ as possible redirect URI into MediaCo_ReactSDK OAuth Client Registration rule - everything works as expected.

**Comment by JEAxero** [comment]
The React SDK isn't yet fully compatible with Pega Infinity 8.7.1. We're working on that now and it will likely require us to distribute new Constellation JS Engine files. However, we'll include this issues in our testing and address them. For this and the other issues that you're reporting, please indicate whether they are related to running against Pega Infinity 8.7.1 (or some other version). Thanks!

**Comment by JEAxero** [comment]
Closing issue since it's been addressed in later updates to the SDK.
