### ISSUE TITLE
Loosing focus from Edit Details local action input fields

### ISSUE THREAD

**Issue by Virusmater** [pegasystems/react-sdk#55]
Steps to reproduce:

1. Create New Service case in portal mode
2. Submit first step
3. Go Action > Edit Details
4. Start typing in Label or Description
Expected
Can type text without any problems
Actual
Every time I type single character - input fields loses its focus. 

Same behavior in both Chrome and Firefox

**Comment by JEAxero** [comment]
The React SDK isn't yet fully compatible with Pega Infinity 8.7.1. We're working on that now and it will likely require us to distribute new Constellation JS Engine files. However, we'll include this issues in our testing and address them. For this and the other issues that you're reporting, please indicate whether they are related to running against Pega Infinity 8.7.1 (or some other version). Thanks!
